name: gateway
description: A new Flutter package.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  json_serializable: ^4.1.2
  dio: ^4.0.0

  domain:
    path: ../domain

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
